[project]
name = "targettts"
version = "0.1.0"
description = "ECE1508 - Target speaker transcription from overlapping speech"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchaudio",
    "soundfile",
    "openai-whisper",
    "transformers",
    "numpy",
    "ipykernel",
    "jiwer>=4.0.0",
    "datasets[audio]",
    "matplotlib>=3.10.8",
    "librosa>=0.11.0",
    "speechbrain>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
