[project]
name = "targettts"
version = "0.1.0"
description = "ECE1508 - Target speaker transcription from overlapping speech"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchaudio",
    "soundfile",
    "openai-whisper",
    "transformers",
    "numpy",
    "ipykernel",
    "jiwer>=4.0.0",
    "datasets[audio]",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true